In [2]:
import numpy as np

In [4]:
A= np.array([[2,1,1],[3,2,1],[2,1,2]])

In [5]:
A

array([[2, 1, 1],
       [3, 2, 1],
       [2, 1, 2]])

In [6]:
A^-1

array([[-3, -2, -2],
       [-4, -3, -2],
       [-3, -2, -3]])

In [7]:
y = np.linalg.inv(A) 
y

array([[ 3., -1., -1.],
       [-4.,  2.,  1.],
       [-1.,  0.,  1.]])